[book]
authors = ["Jérémie Astor"]
language = "en"
multilingual = false
src = "src"
title = "GwionSamples"
description = "Various Gwion Samples"

[output.html]
default-theme = "coal"
git-repository-url ="https://github.com/Gwion/Gwion"

[output.html.playground]
line-numbers= false
editable = true
